version: '3.8'

services:
  nameless_backend_db:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
